import type { ChatSession, ClothingItem, DecisionItem, OutfitIdea, ScoreItem } from "./types";

export const recentChats: ChatSession[] = [
  {
    id: "chat-1",
    title: "米色西装外套",
    subtitle: "通勤穿搭 · 2 小时前",
    favorite: true,
    palette: "from-[#d9b29c] to-[#f0dfd4]",
  },
  {
    id: "chat-2",
    title: "白色运动鞋",
    subtitle: "日常休闲 · 昨天",
    palette: "from-[#f2eee7] to-[#d7c4ad]",
  },
  {
    id: "chat-3",
    title: "黑色连衣裙",
    subtitle: "约会穿搭 · 2 天前",
    palette: "from-[#1f1b1b] to-[#6a5c58]",
  },
  {
    id: "chat-4",
    title: "直筒牛仔裤",
    subtitle: "日常通勤 · 3 天前",
    palette: "from-[#6383a1] to-[#d7e0e8]",
  },
  {
    id: "chat-5",
    title: "棕色托特包",
    subtitle: "通勤搭配 · 5 天前",
    palette: "from-[#a66b43] to-[#e8c6a5]",
  },
];

export const closetItems: ClothingItem[] = [
  {
    id: "closet-1",
    name: "白色衬衫",
    category: "上衣 · 衬衫",
    color: "白色",
    fit: "regular",
    styleTags: ["通勤", "简约"],
    scenarioTags: ["面试", "日常"],
    wearFrequency: "often",
    status: "active",
    palette: "from-[#fbfaf5] to-[#e8ded2]",
  },
  {
    id: "closet-2",
    name: "牛仔直筒裤",
    category: "下装 · 牛仔裤",
    color: "蓝色",
    fit: "regular",
    styleTags: ["休闲", "简约"],
    scenarioTags: ["日常", "通勤"],
    wearFrequency: "often",
    status: "active",
    palette: "from-[#426987] to-[#b2c7d4]",
  },
  {
    id: "closet-3",
    name: "黑色西装外套",
    category: "外套 · 西装",
    color: "黑色",
    fit: "regular",
    styleTags: ["通勤", "干练"],
    scenarioTags: ["面试", "通勤"],
    wearFrequency: "often",
    status: "active",
    palette: "from-[#111111] to-[#77706b]",
  },
  {
    id: "closet-4",
    name: "米色针织衫",
    category: "上衣 · 针织衫",
    color: "米色",
    fit: "regular",
    styleTags: ["休闲", "温柔"],
    scenarioTags: ["日常", "约会"],
    wearFrequency: "sometimes",
    status: "active",
    palette: "from-[#ead9c2] to-[#f8efe2]",
  },
  {
    id: "closet-5",
    name: "碎花连衣裙",
    category: "连衣裙 · 长款",
    color: "浅色",
    fit: "regular",
    styleTags: ["温柔", "度假"],
    scenarioTags: ["旅行", "拍照"],
    wearFrequency: "sometimes",
    status: "active",
    palette: "from-[#f5dcd2] to-[#fff8ef]",
  },
  {
    id: "closet-6",
    name: "白色运动鞋",
    category: "鞋子 · 运动鞋",
    color: "白色",
    fit: "regular",
    styleTags: ["休闲", "百搭"],
    scenarioTags: ["日常", "通勤"],
    wearFrequency: "often",
    status: "active",
    palette: "from-[#f7f5ef] to-[#d4bea7]",
  },
  {
    id: "closet-7",
    name: "卡其色半身裙",
    category: "下装 · 半身裙",
    color: "卡其色",
    fit: "regular",
    styleTags: ["通勤", "温柔"],
    scenarioTags: ["通勤", "约会"],
    wearFrequency: "sometimes",
    status: "active",
    palette: "from-[#c9a47d] to-[#f3dfc8]",
  },
  {
    id: "closet-8",
    name: "灰色卫衣",
    category: "上衣 · 卫衣",
    color: "灰色",
    fit: "oversized",
    styleTags: ["休闲", "慵懒"],
    scenarioTags: ["居家", "日常"],
    wearFrequency: "rarely",
    status: "idle",
    palette: "from-[#a7a7a3] to-[#e2e0dc]",
  },
];

export const scoreItems: ScoreItem[] = [
  { label: "衣橱适配度", value: 92 },
  { label: "搭配潜力", value: 88 },
  { label: "重复购买风险", value: 34 },
  { label: "风格一致性", value: 86 },
  { label: "价格与使用频率", value: 81 },
  { label: "体型/版型友好度", value: 78 },
  { label: "舒适与维护成本", value: 84 },
];

export const outfitIdeas: OutfitIdea[] = [
  {
    id: "outfit-1",
    title: "通勤轻正式",
    scenario: "上班 / 面试前沟通",
    itemIds: ["closet-1", "closet-2", "closet-6"],
    summary: "米色外套压住正式度，白衬衫和直筒裤保持清爽。",
  },
  {
    id: "outfit-2",
    title: "周末咖啡感",
    scenario: "约会 / 城市散步",
    itemIds: ["closet-4", "closet-7", "closet-6"],
    summary: "针织和半裙让外套更柔和，不会像纯通勤套装。",
  },
  {
    id: "outfit-3",
    title: "低成本复用",
    scenario: "日常出门 / 轻商务",
    itemIds: ["closet-2", "closet-3", "closet-5"],
    summary: "已有黑西装能替代一部分场景，新外套的价值在于颜色和季节感。",
  },
];

export const decisionItems: DecisionItem[] = [
  {
    id: "decision-1",
    productName: "通勤西装外套（卡其色）",
    merchant: "UR 官方旗舰店",
    price: 429,
    status: "saved_for_later",
    color: "卡其色",
    size: "M",
    summary: "综合适配度较高，版型百搭，日常通勤和秋季利用率高。",
    outfitTips: ["白衬衫 + 牛仔直筒裤", "针织衫 + 卡其半身裙", "黑西装作替代对照"],
    risks: ["面料较薄，秋冬需叠穿保暖", "卡其色需注意与肤色的托度"],
    lastAskedAt: "2026-06-10 10:35",
    reminderAt: "24 小时后",
    palette: "from-[#caa58e] to-[#f0dfd4]",
  },
  {
    id: "decision-2",
    productName: "德训风休闲板鞋",
    merchant: "回力 官方旗舰店",
    price: 219,
    status: "decided_to_buy",
    color: "白灰",
    size: "38",
    summary: "性价比优秀，好搭耐看，适合日常通勤与休闲搭配。",
    outfitTips: ["牛仔裤 + 白衬衫", "卫衣 + 直筒裤", "半身裙 + 针织衫"],
    risks: ["白色易脏，需要清洁保养", "长时间行走需确认脚感"],
    lastAskedAt: "2026-06-09 16:20",
    palette: "from-[#f4f0e7] to-[#d5bea5]",
  },
  {
    id: "decision-3",
    productName: "黑色无袖连衣裙",
    merchant: "MO&Co. 官方旗舰店",
    price: 599,
    status: "not_considering",
    color: "黑色",
    size: "S",
    summary: "设计简约但使用场景较窄，与已有黑色单品重复度偏高。",
    outfitTips: ["可搭黑色西装", "可用白色运动鞋降正式度"],
    risks: ["场景较单一，日常利用率低", "版型偏修身，对尺码要求较高"],
    lastAskedAt: "2026-06-08 14:02",
    palette: "from-[#171313] to-[#77706b]",
  },
];
